package com.Rifacel.models.Enums;

public enum Department {
    AMAZONAS,
    ANTIOQUIA,
    ARAUCA,
    ATLANTICO,
    BOLIVAR,
    BOYACA,
    CALDAS,
    CAQUETA,
    CASANARE,
    CAUCA,
    CESAR,
    CHOCO,
    CORDOBA,
    CUNDINAMARCA,
    GUAINIA,
    GUAVIARE,
    HUILA,
    LA_GUAJIRA,
    MAGDALENA,
    META,
    NARIÑO,
    NORTE_DE_SANTANDER,
    PUTUMAYO,
    QUINDIO,
    RISARALDA,
    SAN_ANDRES_Y_PROVIDENCIA,
    SANTANDER,
    SUCRE,
    TOLIMA,
    VALLE_DEL_CAUCA,
    VAUPES,
    VICHADA;
}