wompi:
  public-key: ${WOMPI_PUBLIC_KEY}
  private-key: ${WOMPI_PRIVATE_KEY}
  integrity-secret: ${WOMPI_INTEGRITY_SECRET}
  events-key: ${WOMPI_EVENTS_KEY}
  checkout-base-url: https://checkout.wompi.co/p/
  api-base-url: https://production.wompi.co/v1