package com.verygana2.models.enums.legal;

public enum LegalDocumentType {
    USERS_TERMS_AND_CONDITIONS,
    BUSINESS_OWNER_TERMS_AND_CONDITIONS,
    BASIC_PLAN_CONTRACT,
    STANDARD_PLAN_CONTRACT,
    PREMIUM_PLAN_CONTRACT,
    PRIVACY_POLICY,
    DATA_PROCESSING_POLICY,
    COOKIES_POLICY
}
